# Generated by Django 3.2.6 on 2021-12-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message'),
        ('projects', '0009_auto_20211214_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='woner',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
